### PR TITLE
Translate useEffect

### LINKED ISSUE #401: `useEffect`
Page: https://id.react.dev/reference/react/useEffect

Assignee: @R1dwanMaulana

### PR DESCRIPTION
**Pull request by R1dwanMaulana**
Translate for useEffect docs reference by #330

Closes #401

### CODE REVIEW

**Review by r17x — CHANGES_REQUESTED** [review]

**Comment by R1dwanMaulana** [comment]
> @R1dwanMaulana Make sure to also resolve merge conflicts. Your PR has a conflict with the "Scaling Up with Reducer and Context" page for some reason.

done

**Comment by resir014** [comment]
@R1dwanMaulana There are build errors. Please try to fix it and push a new commit.

**Review by resir014 — APPROVED** [review]

**Comment by mhaidarhanif** [comment]
@r17x can check and approve if okay.

**Comment by mazipan** [comment]
Conflict @R1dwanMaulana  :-(

**Comment by R1dwanMaulana** [comment]
> Conflict @R1dwanMaulana :-(

wait I'll redo the clone

**Pull request closed without merging**
