### PR TITLE
docs: translate documentation sidebar at `src/sidebar*.json`

### PR DESCRIPTION
**Pull request by milhamm**
Closes https://github.com/reactjs/id.react.dev/issues/583

## Description

Translate the `src/sidebar*.json`

### CODE REVIEW

**Comment by milhamm** [comment]
Need help translating `Escape Hatches`
cc @resir014

**Comment by resir014** [comment]
Hi @milhamm,

I would recommend you keep the translations as is until the page titles are actually translated. Please coordinate with the other pages to sync the translations.

If the pages are not translated yet, keep it as is.

**Comment by milhamm** [comment]
Will do @resir014 thanks. I've synchronized the sidebar translation only for the pages that are translated

**Review by resir014 — APPROVED** [review]
We're going to merge this for now. For the rest of the untranslated page, we'll continue adding to this as we go. Thanks! @milhamm

**Pull request merged**
