### PR TITLE
fix: translate useEffect

### PR DESCRIPTION
**Pull request by R1dwanMaulana**
translate useEffect

### CODE REVIEW

**Comment by R1dwanMaulana** [comment]
please check again @mhaidarhanif , @resir014 , @mazipan

**Review by mazipan — APPROVED** [review]
Looks good so far 👍

**Comment by R1dwanMaulana** [comment]
> Looks good so far 👍

thanks mas

**Review by resir014 — APPROVED** [review]
All good!

**Comment by R1dwanMaulana** [comment]
> All good!

thanks mas

**Comment by R1dwanMaulana** [comment]
thanks for the correction

**Pull request merged**
